# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebComponent',
            new_name='WebCategories',
        ),
    ]
