# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20180211_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcategories',
            name='ip',
        ),
    ]
