# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20180222_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=80, unique=True)),
                ('finger', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
