# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_appstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstore',
            name='finger',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
