# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_auto_20180222_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstore',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
